language: node_js
node_js:
  - "12.13.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install
script:
- ng lint
- ng build --prod --base-href https://prakashautade.github.io/ShoppingCart/