language: node_js
node_js:
  - "12.13.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install
script:
- ng lint
- npm run test-headless
- npm run e2e
- ng build --prod --base-href https://prakashautade.github.io/ShoppingCart/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ShoppingCart
  on:
    branch: master